WheelofAccess/Controllers/HomeController.cs
 using System;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.Generic;
using WheelofAccess.Models;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using PayPal.Api;
using WheelofAccess.Services.Payment;

namespace WheelofAccess.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            //if (Request.IsAuthenticated)
            //{
            //    string userId = User.Identity.GetUserId();
            //    var myreviews = db.Reviews.Where(x => x.UserId == userId);
            //    ViewBag.Places = db.Places.Count();
            //    ViewBag.Reviews = db.Reviews.Count();
            //    ViewBag.Questions = db.Questions.Count();
            //    ViewBag.MyAnswers = myreviews.Select(x => db.Answers.Where(a => a.ReviewId == x.Id).Count()).Sum();
            //    ViewBag.MyReviews = myreviews.Count();
            //    ViewBag.Users = db.Users.Count();
            //}
            return View();
        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Unlogged()
        {

            return View();
        }
        //[Authorize]
        //public ActionResult Dashboard()
        //{
        //    string userId = User.Identity.GetUserId();
        //    var myreviews = db.Reviews.Where(x => x.UserId == userId);
        //    ViewBag.Places = db.Places.Count();
        //    ViewBag.MyReviews = myreviews.Count();
        //    ViewBag.Reviews = db.Reviews.Count();
        //    ViewBag.Questions = db.Questions.Count();
        //    ViewBag.MyAnswers = myreviews.Select(x => db.Answers.Where(a => a.ReviewId == x.Id).Count()).Sum();
        //    ViewBag.Users = db.Users.Count();
        //    return View();
        //}


    }
}

WheelofAccess/Controllers/MapController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WheelofAccess.Models;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity.Owin;

namespace WheelofAccess.Controllers
{
    public class MapController : Controller
    {
        
        // GET: Map
        public ActionResult Index()
        {
            
            
            return View();
        }
    }
}

WheelofAccess/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WheelofAccess.Managers;
using WheelofAccess.Models;
using WheelofAccess.View_Models;

namespace WheelofAccess.Controllers
{
    public class PlacesController : Controller
    {
        DbManager db = new DbManager();
        // GET: Places
        public ActionResult Index()
        {
            var places = db.GetPlaces();
            return View(places);
        }
        public ActionResult Create()
        {
            PlaceViewModel vm = new PlaceViewModel()
            {
                Place = new Place(),
                Categories = db.GetCategories().Select(x => new SelectListItem()
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                })

            };

            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PlaceViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }
            db.AddPlace(vm.Place, vm.SelectedCategories);
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            var place = db.GetPlaceDetails(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            PlaceViewModel vm = new PlaceViewModel()
            {
                Place = place,
                Categories = db.GetCategories().Select(x => new SelectListItem()
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                })
            };
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PlaceViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }
            db.EditPlace(vm.Place, vm.SelectedCategories);
            return RedirectToAction("Index");
        }
        [Authorize(Roles ="Admin")]
        public ActionResult Delete(int id)
        {
            var place = db.GetPlaceDetails(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            PlaceViewModel vm = new PlaceViewModel()
            {
                Place = place,
                Categories = db.GetCategories().Select(x => new SelectListItem()
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                }),

            };
            return View(place);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Place place)
        {
            
            
            
            db.DeletePlace(place);
            return RedirectToAction("Index");
        }



    }
}
    

WheelofAccess/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WheelofAccess.Managers;
using WheelofAccess.Models;
using System.Data.Entity.Infrastructure;

namespace WheelofAccess.Controllers
{
    public class QuestionsController : Controller
    {
        DbManager db = new DbManager();
        // GET: Questions
        [Authorize]
        public ActionResult Index()
        {            
            var questions=db.GetQuestions();
            return View(questions); 
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.PossibleAnswers = new SelectList(db.GetAnswerOptions(), "Id","Answer");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Question question)
        {
            if (!ModelState.IsValid)
            {
                return View(question);
            }
            db.AddQuestion(question);

            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {

            var question=db.FindQuestion(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(Question question)
        {
            if (!ModelState.IsValid)
            {
                return View(question);
            }
            db.EditQuestion(question);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var question=db.FindQuestion(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(Question question)
        {
            if (!ModelState.IsValid)
            {
                return View(question);
            }
            db.DeleteQuestion(question);
            return RedirectToAction("Index");
        }

      
    }
}

WheelofAccess/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WheelofAccess.Models;
using WheelofAccess.Managers;

namespace WheelofAccess.Controllers
{
    [Authorize] 
    public class ReviewsController : Controller
    {
        private DbManager db = new DbManager();

        // GET: Reviews
        public ActionResult Index()
        {
            var id =User.Identity.GetUserId();
            var reviews =db.GetUsersReviews(id);
            return View(reviews);
        }      

        // GET: Reviews/Create
        public ActionResult Create()
        {
            ViewBag.PlaceId = new SelectList(db.GetPlaces(), "Id", "Name");

            return View();
        }

        // POST: Reviews/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Comment,PlaceId")] Review review)
        {
            if (!ModelState.IsValid)
            {
                return View(review);
            }
            review.UserId=User.Identity.GetUserId();
           
            db.CreateReview(review);
            ViewBag.PlaceId = new SelectList(db.GetPlaces(), "Id", "Name");
            return RedirectToAction("Index");          
        }
      
        [HttpGet]
        // GET: Reviews/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Questions = db.GetQuestions();
            var review = db.FindReview(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            if (review.UserId != User.Identity.GetUserId())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            ViewBag.PlaceId = new SelectList(db.GetPlaces(), "Id", "Name");
            ViewBag.PlaceName = db.GetPlaces().Where(p => p.Id == review.PlaceId).FirstOrDefault().Name;
            return View(review);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Review review)
        {
            if (!ModelState.IsValid)
            {
                return View(review);
            }
            db.EditReview(review);
            return RedirectToAction("Index");

        }
        

        

        // GET: Reviews/Delete/5
        public ActionResult Delete(int id)
        {
            var review = db.FindReview(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            if (review.UserId != User.Identity.GetUserId())
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete([Bind(Include = "Id,Rating,Comment,PlaceId")]Review review)
        {
            if (!ModelState.IsValid)
            {
                return View(review);
            }
            review.UserId=User.Identity.GetUserId();
            db.DeleteReview(review);
            return RedirectToAction("Index");
        }  
    }
}

WheelofAccess/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - Wheel Of Access</title>
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="icon" href="~/img/templogo.png">
    <!-- Custom styles for this template-->
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/Account.css" rel="stylesheet">
    <!-- Custom fonts for this template-->

    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">


</head>
<body>
    <div style="height: 100%;align-content: center">
        <div class="d-flex justify-content-center h-100">
            @RenderBody();
            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)
        </div>
    </div>
</body>
</html>

WheelofAccess/Views/Shared/_Footer.cshtml
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Wheel Of Access 2019</span>
        </div>
    </div>
</footer>

WheelofAccess/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - Wheel Of Access</title>
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="~/img/templogo.png">
    <!-- Custom fonts for this template-->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <!-- Custom styles for this template-->
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/style.css" rel="stylesheet">

    @RenderSection("styles", required: false)
</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        @if (Request.IsAuthenticated)
        {
            @Html.Partial("_Sidebar")
        }
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                @if (Request.IsAuthenticated)
                {
                    @Html.Partial("~/Views/Shared/_Topbar.cshtml ")
                }

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <style>
                        /* Set the size of the div element that contains the map */
                        #map {
                            height: 500px;
                            width: 100%;
                            padding-bottom: 1rem;
                        }
                    </style>
                    @RenderBody()
                </div>
            </div>
            <!-- /.container-fluid -->
            <!-- End of Main Content -->
            <!-- Footer -->

             @Html.Partial("~/Views/Shared/_Footer.cshtml ")

            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    @Scripts.Render("~/bundles/jquery")
    <!-- Core plugin JavaScript-->
    <script src="~/Scripts/jquery.easing.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <!-- Custom scripts for all pages-->
    <script src="~/Scripts/main.js"></script>
    @RenderSection("scripts", required: false)
    

</body>

</html>

WheelofAccess/Views/Shared/_Sidebar.cshtml
@using Microsoft.AspNet.Identity

    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        @Html.ActionLink("Wheel of Access", "Index", "Home", new { area = "" }, new { @class = "sidebar-brand d-flex align-items-center justify-content-center" })

        <!-- Divider -->
        <hr class="sidebar-divider my-0">


        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
           <p class="nav-link" >
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span>
            </p>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            Interface
        </div>

        <!-- Nav Item - Map -->
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Map")">
                <i class="fas fa-fw fa-map"></i>
                <span>Map</span>
            </a>
        </li>

        <!-- Nav Item - Places -->
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Places")">
                <i class="fas fa-fw fa-map-marker-alt"></i>
                <span>Places</span>
            </a>
        </li>

        <!-- Nav Item - Reviews Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseReviews" aria-expanded="true" aria-controls="collapseReviews">
                <i class="fas fa-fw fa-star"></i>
                <span>Reviews</span>
            </a>
            <div id="collapseReviews" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Manage:</h6>
                    @Html.ActionLink("All", "Index", "Reviews", new { }, new { @class = "collapse-item" })
                    @Html.ActionLink("Add New", "Create", "Reviews", new { }, new { @class = "collapse-item" })
                </div>
            </div>
        </li>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-fw fa-file"></i>
                <span>Pages</span>
            </a>
            <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">About this app</h6>
                    @Html.ActionLink("Landing Page", "Unlogged", "Home", new { }, new { @class = "collapse-item" })
                </div>
            </div>
        </li>


        <!-- Divider -->
        <hr class="sidebar-divider">

        @if (User.IsInRole("Admin"))
        {
            <!-- Heading -->
            <div class="sidebar-heading">
                Admin Area
            </div>

            <!-- Nav Item - Users -->
            <li class="nav-item">
                <a class="nav-link" href=@Url.Action("Index", "Admin")>
                    <i class="fas fa-fw fa-user"></i>
                    <span>Users</span>
                </a>
            </li>

            <!-- Nav Item - Questions Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseQuestions" aria-expanded="true" aria-controls="collapseQuestions">
                    <i class="fas fa-fw fa-question"></i>
                    <span>Questions</span>
                </a>
                <div id="collapseQuestions" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Manage:</h6>
                        @Html.ActionLink("All", "Index", "Questions", new { }, new { @class = "collapse-item" })
                        @Html.ActionLink("Add New", "Create", "Questions", new { }, new { @class = "collapse-item" })
                    </div>
                </div>
            </li>


            <!-- Nav Item - Answers Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAnswers" aria-expanded="true" aria-controls="collapseAnswers">
                    <i class="fas fa-fw fa-list"></i>
                    <span>Possible Answers</span>
                </a>
                <div id="collapseAnswers" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Manage:</h6>
                        @Html.ActionLink("All", "Index", "PossibleAnswers", new { }, new { @class = "collapse-item" })
                        @Html.ActionLink("Add New", "Create", "PossibleAnswers", new { }, new { @class = "collapse-item" })
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

        }

        <!-- Nav Item - Donation -->
        <li class="nav-item">
            <a class="nav-link" href="/PayPal/PaymentWithPaypal/">
                <i class="fas fa-fw fa-heart"></i>
                <span>Donate</span>
            </a>
        </li>

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="text-center d-none d-md-inline rounded-circle border-0" id="sidebarToggle"></button>
        </div>
    </ul>

WheelofAccess/Views/Shared/_Topbar.cshtml
    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        @*<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
        </form>*@

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
                <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-search fa-fw"></i>
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                    <form class="form-inline mr-auto w-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </li>

            @Html.Partial("_LoginPartial")
        </ul>

    </nav>
    <!-- End of Topbar -->

WheelofAccess/Views/Shared/_TopbarUnlogged.cshtml
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">WOA</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="~/#about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="~/#map2">Map</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="~/#signup">Join</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="~/#contact">Contact</a>
                </li>
                @if (Request.IsAuthenticated)
                {
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="@Url.Action("Index", "Home")">Dashboard</a>
                </li>
                }
            </ul>

            <ul class="navbar-nav ml-auto">
                @Html.Partial("_LoginPartial")
            </ul>
        </div>
    </div>
</nav>

WheelofAccess/Views/Shared/_UnloggedLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - Wheel Of Access</title>
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="~/img/templogo.png">
    <!-- Custom styles for this template-->
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/Account.css" rel="stylesheet">
    <link href="~/Content/styleUnlogged.css" rel="stylesheet">
    <!-- Custom fonts for this template-->

    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

</head>

<body>
    @RenderBody()
    <!-- Custom scripts for this template -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <!-- Core plugin JavaScript-->
    <script src="~/Scripts/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/Scripts/mainUnlogged.js"></script>
    <!--Script for external google login trigger-->
    <script>
        $("#external-google").on("click", function () {
            $("#Google").click();
        })
    </script>
    <!--Scripts for the map-->

    @RenderSection("scripts", required: false)

</body>

</html>